name: CI Build Linux Binary

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  call-workflow-ci-build:
    uses: ./.github/workflows/build.yml

  build-native:
    name: dnsmap client on ubuntu-latest
    needs: call-workflow-ci-build
    runs-on: ubuntu-latest
    steps:
      - name: Download java-build
        uses: actions/download-artifact@v3
        with:
          name: package
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Compile to native binary
        run: native-image --no-fallback -cp client-app/build/libs/client-*.jar -H:Class=ch.dnsmap.dnsm.application.DnsmClientAppKt -H:Name=dnsm  --enable-url-protocols=https
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: native-ubuntu-latest
          path: dnsm*
