name: CI

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: core/build/reports/
      - name: Archive artefacts
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            client/build/libs/
            core/build/libs/

  build-native:
    name: dnsmap client on ${{ matrix.os }}
    needs: build-java
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Download java-build
        uses: actions/download-artifact@v3
        with:
          name: package
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Compile to native
        run: native-image --no-fallback -cp client/build/libs/client-*.jar -H:Class=ch.dnsmap.dnsm.infrastructure.ClientKt -H:Name=dnsm
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: native-${{ matrix.os }}
          path: dnsm{,.exe}
