name: CI Release

on:
  push:
    tags:
      - v*

jobs:
  call-workflow-ci-build:
    uses: ./.github/workflows/build.yml

  build-native:
    name: dnsmap client on ${{ matrix.os }}
    needs: call-workflow-ci-build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Download java-build
        uses: actions/download-artifact@v3
        with:
          name: package
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Compile to native binary
        run: native-image --no-fallback -cp client-app/build/libs/client-*.jar -H:Class=ch.dnsmap.dnsm.application.DnsmClientAppKt -H:Name=dnsm
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: native-${{ matrix.os }}
          path: dnsm*
